spring:
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
            default-filters:
            routes:
                -   id: user
                    uri: lb://user
                    predicates:
                        - Path=/user/**
                    filters:
                        - RewritePath=/user/(?<path>.*), /$\{path}
                        -   name: Hystrix
                            args:
                                name: userHystrixCommand
                                fallbackUri: forward:/hystrixTimeout
    
                -   id: websocket
                    uri: lb:ws://websocket
                    predicates:
                        - Path= ${server.servlet.context-path}/websocket/**
                    filters:
                        - StripPrefix= 1






logging:
    level:
        cn.ff: debug
