

# TODO 需要加密！！！ !!! ！！！ !!! ！！！ !!!
auth:
    clientId: adc
    clientSecret: sss
    scope: server
    urls:
        - /authentication/**
        - /**/*.css
        - /social
        - /signin
        - /signup
        - /info
        - /health
        - /metrics/**
        - /loggers/**
        - /mobile/token
        - /test/**


spring:
  mvc:
    view:
      prefix: /
      suffix: .html
  

security:
  oauth2:
    resource:
      filter-order: 3