
server:
  port: 9120
spring:
  application:
    name: user

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost/hs_user?useUnicode=true&characterEncoding=utf-8
    username: root
    password: '{cipher}AQCxzWHfmcUDpm6zu4/HPxgl8uZqmU7yfgOLBIZnNl70o2tdylxDQX7t2NeiGLbv9jTBU+/FGs3kwHMt0bdPt/CDXrY4MrGwmJalnG8sRAI326zmtASPJVYRaCiS4w0jxxRTzsK00XJtZ2D+fNfQOFExXZJ44wBXR5gWYPwNXH+eMniTuPr37pkJeqYoHJQPpg/eFl3aAjOb6wxN9YyesGZF+Vp2eO+C94DwpMuR1cdABXz2fYEy4pGV2kL83zZBftP6YPUK4BGku0j6Gqaghl9fsqBlSlajBoA+Mce5+iLzitQmvgVUFaVoUPuE2QQC67eChIbsutiGGZ5BaGHO/TvgRheIK/yuh+h/GNjFDhAkEidvAl6Nm0k4ujQAtFu/PBM='
  rabbitmq:
    host: 39.107.123.121
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/


from: git.user.dev-1.0
testPwd: '{cipher}AQCyv1J8OlOssbCRnN9Hg1WqCCqkyUqsn9WLvyDbx58LCiD4xvcUvWFQhFteDI52tkBMLlCFkl9Z61wjkHyQtNZPF+mBid35604HkNk/Z7oF/lMBDQTzPZSjiTZT0OiQSHKO8jF4c+LyDnkYDEhWV9A4t6JKVLN3+ib5twqubZk+jyJ9eSQ9Mdh0ggcDEKhr7LzwwOkUsbtK6mfY2K95yWI0+E0m9hKQkxAxXeKsjh0AuTfy+2jGxcL+wghmwMlxKQg/ZJEMkP71xx1F7MQ83w7ncruxNI7yBxcJUC7Ot9mzPIZQwxT/mOtgFfhltG/GwLSqYnRUgzqrx39vdMnYwpu0NOir67/oLS9LHBPPGwGfUbqKsdxFF7icbkaWJxVX0VA='


mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: cn.heartStack.user
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false



logging:
    level:
        cn:
            heartStack:
                user:
                    mapper: DEBUG